version: '3.8'

services:
  backend1:
    build: .
    container_name: backend1
    environment:
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - ./logs:/usr/src/app/logs
    depends_on:
      - mongo
    networks:
      - backend_network
    ports:
    - "3000:3000"
    command: bash -c "npm install && node scripts/initData.js && npm start"

  backend2:
    build: .
    container_name: backend2
    environment:
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - ./logs:/usr/src/app/logs
    depends_on:
      - mongo
    networks:
      - backend_network
    ports:
    - "3001:3000"
    command: bash -c "npm install && node scripts/initData.js && npm start" 

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "5000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend1
      - backend2
    networks:
      - backend_network

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - backend_network

volumes:
  mongo_data:

networks:
  backend_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16