version: '3.8'

services:
  backend:
    build: .
    container_name: concert_backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/concertdb
      JWT_SECRET: "super_secret_key"
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo:6
    container_name: concert_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
