version: '3.8'

services:
  backend:
    build: .
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/concertdb
      JWT_SECRET: "super_secret_key"
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/usr/src/app/logs

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

volumes:
  mongo_data:
